name: "MD-personal-website"
navbar:
  title: "MD personal website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
    - text: "Publications"
      href: publications.html
    - text: "CV"
      href: cv.html
theme: jekyll-theme-minimal
